services:
  - type: web
    name: wifi-threat-api
    env: python
    buildCommand: ""
    startCommand: uvicorn predict_api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
